[FIX] account_chatter: Account move narration field is html field not text
This module reassigns the narration field type, from html to text, that
was wrong because when the field being refereced from a related field
following error appears

	TypeError: Type of related field bank.rec.widget.st_line_narration is
	inconsistent with account.move.narration

So we remove the field inheritance, because the only reason this field
was inherited was to make it trackeable, which is not supported for
HTML fields.