[FIX] comment the import of res_partner file because the instance was returning an error. This module is not in use.
Here a copy of the traceback::

      File "/home/kathy/vx/git/vauxoo/addons-vauxoo/account_advance_payment/__init__.py", line 26, in <module>
        from . import model
      File "/home/kathy/vx/git/vauxoo/addons-vauxoo/account_advance_payment/model/__init__.py", line 27, in <module>
        from . import res_partner
      File "/home/kathy/vx/git/vauxoo/addons-vauxoo/account_advance_payment/model/res_partner.py", line 29, in <module>
        class res_partner(osv.Model):
      File "/home/kathy/vx/git/vauxoo/addons-vauxoo/account_advance_payment/model/res_partner.py", line 46, in res_partner
        help="This account will be used for advance payment of suppliers"),
    TypeError: __init__() takes exactly 1 argument (8 given)